<?php
/*
Plugin Name: GitHub Code Embedder
Plugin URI: http://vamsisangam.com/
Description: A simple WordPress plugin to embed source code hosted on GitHub with syntax highlighting.
Version: 1.0
Author: Vamsi Sangam
Author URI: http://vamsisangam.com
License: MIT
*/
if (is_admin()) {
    /* Call the html code */
    add_action('admin_menu', 'github_code_embedder_admin_menu');

    function github_code_embedder_admin_menu() {
        add_options_page('GitHub Code Embedder', 'GitHub Code Embedder', 'administrator',
        'github_code_embedder', 'github_code_embedder_html_page');
    }
}

function github_code_embedder_wp_footer() {
    ?>
    <!-- Scripts for GitHub Code Embedder -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/line-numbers/prism-line-numbers.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/components/prism-c.min.js"></script>
    <script>
            $(document).ready(function () {
                $('.dynamic-prism code').each(function (index) {
                    var url = $(this).attr("data-github-raw");
                    var pre = $(this);

                    $.get(url, function (data) {
                        pre.text(data);
                        Prism.highlightAll();
                    });
                });
            });
        </script>
    <?php
}

add_action('wp_footer', 'github_code_embedder_wp_footer');

function github_code_embedder_wp_head() {
    ?>
    <!-- Styles for GitHub Code Embedder -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/line-numbers/prism-line-numbers.min.css"/>
    
    <?php
}

add_action('wp_head', 'github_code_embedder_wp_head');

function gh_code_func($atts) {
    ?>
    <!-- Generated by GitHub code embedder -->
    <pre class="dynamic-prism language-<?= $atts['lang'] ?> line-numbers">
        <code data-github-raw="<?= $atts['url'] ?>"></code>
    </pre>
    <?php
}

add_shortcode( 'gh_code', 'gh_code_func' );

function github_code_embedder_html_page() {
    wp_enqueue_style('materialize.min.css', 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css');
    wp_enqueue_script('materialize.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js');
    ?>
        <h4>GitHub Code Embedder</h4>
        <p>
            GitHub Code Embedder enables you to easily display source codes on your website which are hosted by means of GitHub repositories or Gists. This is the plugin settings page where you can customize the plugin functionalities according to your requirement.
        </p>
        <h5>Select a theme</h5>
        <form action="#">
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-default" />
                <label class="black-text" for="theme-default">Default</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-dark" />
                <label class="black-text" for="theme-dark">Dark</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-funky" />
                <label class="black-text" for="theme-funky">Funky</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-okaidia" />
                <label class="black-text" for="theme-okaidia">Okaidia</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-twilight" />
                <label class="black-text" for="theme-twilight">Twilight</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-coy" />
                <label class="black-text" for="theme-coy">Coy</label>
            </p>
            <p>
                <input class="with-gap" name="theme" type="radio" id="theme-solarized-light" />
                <label class="black-text" for="theme-solarized-light">Solarized Light</label>
            </p>
            <br>
            <button class="btn green waves-effect">Confirm</button>
        </form>
        <br>
        <h5>Line Numbers</h5>
        <p>
            By activating this option your code will be displayed along with line numbers. By activating this, you can also specify a <b>start-number</b> which will make the line counter start with the specified number.
        </p>
        <div class="switch">
            <label>
                Off
                <input type="checkbox">
                <span class="lever"></span>
                On
            </label>
        </div>
        <br>
        <h5>Line Highlight</h5>
        <p>
            By activating this you can highlight certain specific lines in your code. You can highlight single or group of lines. Use <b>line-highlight</b> attribute to specify line numbers. Usage -
        </p>
        <div class="row">
            <div class="col s4">
                <ul class="collapsible" data-collapsible="accordion" style="background-color: white">
                    <li>
                        <div class="collapsible-header">Highlight single line</div>
                        <div class="collapsible-body">
                            <p>
                                <code>line-highlight="5"</code>
                            </p>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header">Highlight a range of lines</div>
                        <div class="collapsible-body">
                            <p>
                                <code>line-highlight="1-5"</code>
                            </p>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header">Highlight multiple single lines</div>
                        <div class="collapsible-body">
                            <p>
                                <code>line-highlight="1,4"</code>
                            </p>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header">Highlight any combination of above</div>
                        <div class="collapsible-body">
                            <p>
                                <code>line-highlight="1-2,5,9-20"</code>
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <button class="btn green waves-effect">Activate Line numbers</button>
        <button class="btn red waves-effect">Deactivate Line numbers</button>
        <br><br>
        <h5>About Plugin</h5>
        <br>
        <style>
        a.blue:hover {
            color:white;
        }
        </style>
        <a class="blue waves-effect waves-light btn">GitHub</a> &nbsp;
        <a class="blue waves-effect waves-light btn">WordPress</a> &nbsp;
        <a class="blue waves-effect waves-light btn">Developer</a>
    <?php
}
?>